apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: encoder-pvc
spec:
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 5Gi

