apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        namespace: sy
        name: sang-csv-pvc
spec:
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 10Gi
