# Generated by Django 4.0.3 on 2023-09-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonpaItem1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_img', models.TextField(blank=True, null=True)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('before_now', models.FloatField(blank=True, null=True)),
                ('before_one', models.FloatField(blank=True, null=True)),
                ('before_two', models.FloatField(blank=True, null=True)),
                ('before_three', models.FloatField(blank=True, null=True)),
                ('before_four', models.FloatField(blank=True, null=True)),
                ('before_five', models.FloatField(blank=True, null=True)),
                ('before_six', models.FloatField(blank=True, null=True)),
                ('before_seven', models.FloatField(blank=True, null=True)),
                ('before_eight', models.FloatField(blank=True, null=True)),
                ('before_nine', models.FloatField(blank=True, null=True)),
                ('before_ten', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donpa_item1',
                'managed': False,
            },
        ),
    ]
