# Generated by Django 4.0.3 on 2023-09-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_donpanews'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonpaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('herf', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donpa_event',
                'managed': False,
            },
        ),
    ]
