# Generated by Django 4.0.3 on 2023-09-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_donpaevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputList',
            fields=[
                ('title', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('jobname', models.TextField(blank=True, null=True)),
                ('emblem', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'input_list',
                'managed': False,
            },
        ),
    ]
