apiVersion: batch/v1
kind: CronJob
metadata:
  name: item-cj9
spec:
  schedule: "20 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: item-cj9
        spec:
          restartPolicy: OnFailure
          containers:
          - name: item-cronjob9
            image: kubeflow-registry.default.svc.cluster.local:30000/donpa_item10:latest
