apiVersion: batch/v1
kind: CronJob
metadata:
  name: item-cj5
spec:
  schedule: "20 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: item-cj5
        spec:
          restartPolicy: OnFailure
          containers:
          - name: item-cronjob5
            image: kubeflow-registry.default.svc.cluster.local:30000/donpa_item6:latest
