apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: db-pvc
        namespace: sy
spec:
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 3Gi
