apiVersion: v1
kind: Service
metadata:
  namespace: sy
  name: mariadb-service
spec:
  selector:
    app: mariadb  
  ports:
    - protocol: TCP
      port: 3306 
      targetPort: 3306
      nodePort: 31234
  type: NodePort
