apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        namespace: sy
        name: katib-yaml-pvc
spec:
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 1Gi

