apiVersion: v1
kind: Service
metadata:
  name: donpa-django-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000  # 실제 MariaDB 파드의 포트
      nodePort: 30001
  selector:
    app: donpa-django-rs
